# Site settings
title: Colégio Alumni Arautos do Oeste Nº 10
email: contato@colegioarautosdooeste.com.br
url: colegioarautosdooeste.com.br
description: "Pagina do Colegio Alumni Arautos do Oeste, vinculado ao Capitulo Cascavel 425"
keywords: "Colegio Alumni, Alumni, DeMolay, Capitulo Cascavel"
skills: "Informações sobre o 1º Churrasco da Associação DeMolay Alumni do Estado do Paraná - ADAE-PR"
meta_author: Arautos do Oeste

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00DAE7 #80B3FF
  primary-rgb: "0,218,231" #"128,179,255"
  secondary: 003A40 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  location: Local do Evento
  social: Rede Social
  credits: Dúvidas

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/arautosdooeste10
    
# Postal address (add as many lines as necessary)
address:
  - line: Chácara Cobezal
  - line: Rua XYZ, Nº 133 - Após Tal Lugar

# Credits content
credits: 'Ir. Guilherme Konig - (45) 99825-XXXX'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
